target-version = "py310"
line-length = 120

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM"]
ignore = ["E501", "SIM105"]

[lint.per-file-ignores]
"src/ui/styles.py" = ["W293"]

[lint.isort]
known-first-party = ["src"]

[format]
quote-style = "double"
